version: '3.8'

services:
  # --- Reverse Proxy (El sem√°foro del Blue/Green) ---
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-blue
      - app-green

  # --- Microservicios (Dos colores) ---
  app-blue:
    build: .
    container_name: app-blue
    environment:
      - PORT=3000
    ports:
      - "3001:3000" # Acceso directo para pruebas

  app-green:
    build: .
    container_name: app-green
    environment:
      - PORT=3000
    ports:
      - "3002:3000" # Acceso directo para pruebas

  # --- Monitoreo [cite: 34] ---
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"