global:
  scrape_interval: 5s # Scrape frecuente para ver cambios r√°pido en la demo

scrape_configs:
  - job_name: 'transaction_validator'
    static_configs:
      # Escucha a ambos contenedores (Blue y Green)
      - targets: ['app-blue:3000', 'app-green:3000']